name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: test
      run: |
        xcodebuild clean test -workspace Bible.xcworkspace -scheme Bible -destination 'platform=iOS Simulator,OS=13.6,name=iPhone 11 Pro Max'
